In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [7]:
data_dir = r"./../data/raw"

files = sorted([f for f in os.listdir(data_dir) if f.endswith(".csv")])
print(files)

['POS_CASH_balance.csv', 'application_test.csv', 'application_train.csv', 'bureau.csv', 'bureau_balance.csv', 'credit_card_balance.csv', 'installments_payments.csv', 'previous_application.csv']

In [8]:
for file in files:
    print(os.path.join(data_dir, file))
    df = pd.read_csv(os.path.join(data_dir, file))
    total_rows = len(df)
    null_counts = df.isnull().sum()
    null_summary = pd.DataFrame({
        "null_count": null_counts,
        "null_percentage": (null_counts / total_rows * 100).round(2)
    })
    null_summary = null_summary[null_summary["null_count"] > 0].sort_values(
        by="null_count", ascending=False
    )

    print(f"\n{'=' * 80}")
    print(f"Table: {file} | Rows: {total_rows:,} | Columns: {df.shape[1]}")

    if null_summary.empty:
        print("No null values found.")
    else:
        print(null_summary.to_string())

./../data/raw/POS_CASH_balance.csv

================================================================================
Table: POS_CASH_balance.csv | Rows: 10,001,358 | Columns: 8
                       null_count  null_percentage
CNT_INSTALMENT_FUTURE       26087             0.26
CNT_INSTALMENT              26071             0.26
./../data/raw/application_test.csv

================================================================================
Table: application_test.csv | Rows: 48,744 | Columns: 121
                              null_count  null_percentage
COMMONAREA_AVG                     33495            68.72
COMMONAREA_MODE                    33495            68.72
COMMONAREA_MEDI                    33495            68.72
NONLIVINGAPARTMENTS_AVG            33347            68.41
NONLIVINGAPARTMENTS_MODE           33347            68.41
NONLIVINGAPARTMENTS_MEDI           33347            68.41
FONDKAPREMONT_MODE                 32797            67.28
LIVINGAPARTMENTS_MODE              32780            67.25
LIVINGAPARTMENTS_AVG               32780            67.25
LIVINGAPARTMENTS_MEDI              32780            67.25
FLOORSMIN_MEDI                     32466            66.61
FLOORSMIN_AVG                      32466            66.61
FLOORSMIN_MODE                     32466            66.61
OWN_CAR_AGE                        32312            66.29
YEARS_BUILD_MODE                   31818            65.28
YEARS_BUILD_AVG                    31818            65.28
YEARS_BUILD_MEDI                   31818            65.28
LANDAREA_MEDI                      28254            57.96
LANDAREA_MODE                      28254            57.96
LANDAREA_AVG                       28254            57.96
BASEMENTAREA_AVG                   27641            56.71
BASEMENTAREA_MODE                  27641            56.71
BASEMENTAREA_MEDI                  27641            56.71
NONLIVINGAREA_MODE                 26084            53.51
NONLIVINGAREA_AVG                  26084            53.51
NONLIVINGAREA_MEDI                 26084            53.51
ELEVATORS_MODE                     25189            51.68
ELEVATORS_AVG                      25189            51.68
ELEVATORS_MEDI                     25189            51.68
WALLSMATERIAL_MODE                 23893            49.02
APARTMENTS_MODE                    23887            49.01
APARTMENTS_AVG                     23887            49.01
APARTMENTS_MEDI                    23887            49.01
HOUSETYPE_MODE                     23619            48.46
ENTRANCES_AVG                      23579            48.37
ENTRANCES_MODE                     23579            48.37
ENTRANCES_MEDI                     23579            48.37
LIVINGAREA_MODE                    23552            48.32
LIVINGAREA_AVG                     23552            48.32
LIVINGAREA_MEDI                    23552            48.32
FLOORSMAX_AVG                      23321            47.84
FLOORSMAX_MODE                     23321            47.84
FLOORSMAX_MEDI                     23321            47.84
YEARS_BEGINEXPLUATATION_MEDI       22856            46.89
YEARS_BEGINEXPLUATATION_MODE       22856            46.89
YEARS_BEGINEXPLUATATION_AVG        22856            46.89
TOTALAREA_MODE                     22624            46.41
EMERGENCYSTATE_MODE                22209            45.56
EXT_SOURCE_1                       20532            42.12
OCCUPATION_TYPE                    15605            32.01
EXT_SOURCE_3                        8668            17.78
AMT_REQ_CREDIT_BUREAU_MON           6049            12.41
AMT_REQ_CREDIT_BUREAU_QRT           6049            12.41
AMT_REQ_CREDIT_BUREAU_YEAR          6049            12.41
AMT_REQ_CREDIT_BUREAU_HOUR          6049            12.41
AMT_REQ_CREDIT_BUREAU_DAY           6049            12.41
AMT_REQ_CREDIT_BUREAU_WEEK          6049            12.41
NAME_TYPE_SUITE                      911             1.87
DEF_30_CNT_SOCIAL_CIRCLE              29             0.06
OBS_30_CNT_SOCIAL_CIRCLE              29             0.06
OBS_60_CNT_SOCIAL_CIRCLE              29             0.06
DEF_60_CNT_SOCIAL_CIRCLE              29             0.06
AMT_ANNUITY                           24             0.05
EXT_SOURCE_2                           8             0.02
./../data/raw/application_train.csv

================================================================================
Table: application_train.csv | Rows: 307,511 | Columns: 122
                              null_count  null_percentage
COMMONAREA_MEDI                   214865            69.87
COMMONAREA_MODE                   214865            69.87
COMMONAREA_AVG                    214865            69.87
NONLIVINGAPARTMENTS_MODE          213514            69.43
NONLIVINGAPARTMENTS_MEDI          213514            69.43
NONLIVINGAPARTMENTS_AVG           213514            69.43
FONDKAPREMONT_MODE                210295            68.39
LIVINGAPARTMENTS_AVG              210199            68.35
LIVINGAPARTMENTS_MEDI             210199            68.35
LIVINGAPARTMENTS_MODE             210199            68.35
FLOORSMIN_MEDI                    208642            67.85
FLOORSMIN_MODE                    208642            67.85
FLOORSMIN_AVG                     208642            67.85
YEARS_BUILD_MODE                  204488            66.50
YEARS_BUILD_MEDI                  204488            66.50
YEARS_BUILD_AVG                   204488            66.50
OWN_CAR_AGE                       202929            65.99
LANDAREA_AVG                      182590            59.38
LANDAREA_MEDI                     182590            59.38
LANDAREA_MODE                     182590            59.38
BASEMENTAREA_MODE                 179943            58.52
BASEMENTAREA_MEDI                 179943            58.52
BASEMENTAREA_AVG                  179943            58.52
EXT_SOURCE_1                      173378            56.38
NONLIVINGAREA_MEDI                169682            55.18
NONLIVINGAREA_AVG                 169682            55.18
NONLIVINGAREA_MODE                169682            55.18
ELEVATORS_MEDI                    163891            53.30
ELEVATORS_MODE                    163891            53.30
ELEVATORS_AVG                     163891            53.30
WALLSMATERIAL_MODE                156341            50.84
APARTMENTS_AVG                    156061            50.75
APARTMENTS_MEDI                   156061            50.75
APARTMENTS_MODE                   156061            50.75
ENTRANCES_MODE                    154828            50.35
ENTRANCES_MEDI                    154828            50.35
ENTRANCES_AVG                     154828            50.35
LIVINGAREA_AVG                    154350            50.19
LIVINGAREA_MODE                   154350            50.19
LIVINGAREA_MEDI                   154350            50.19
HOUSETYPE_MODE                    154297            50.18
FLOORSMAX_AVG                     153020            49.76
FLOORSMAX_MEDI                    153020            49.76
FLOORSMAX_MODE                    153020            49.76
YEARS_BEGINEXPLUATATION_MODE      150007            48.78
YEARS_BEGINEXPLUATATION_MEDI      150007            48.78
YEARS_BEGINEXPLUATATION_AVG       150007            48.78
TOTALAREA_MODE                    148431            48.27
EMERGENCYSTATE_MODE               145755            47.40
OCCUPATION_TYPE                    96391            31.35
EXT_SOURCE_3                       60965            19.83
AMT_REQ_CREDIT_BUREAU_WEEK         41519            13.50
AMT_REQ_CREDIT_BUREAU_MON          41519            13.50
AMT_REQ_CREDIT_BUREAU_HOUR         41519            13.50
AMT_REQ_CREDIT_BUREAU_YEAR         41519            13.50
AMT_REQ_CREDIT_BUREAU_QRT          41519            13.50
AMT_REQ_CREDIT_BUREAU_DAY          41519            13.50
NAME_TYPE_SUITE                     1292             0.42
DEF_30_CNT_SOCIAL_CIRCLE            1021             0.33
DEF_60_CNT_SOCIAL_CIRCLE            1021             0.33
OBS_30_CNT_SOCIAL_CIRCLE            1021             0.33
OBS_60_CNT_SOCIAL_CIRCLE            1021             0.33
EXT_SOURCE_2                         660             0.21
AMT_GOODS_PRICE                      278             0.09
AMT_ANNUITY                           12             0.00
CNT_FAM_MEMBERS                        2             0.00
DAYS_LAST_PHONE_CHANGE                 1             0.00
./../data/raw/bureau.csv

================================================================================
Table: bureau.csv | Rows: 1,716,428 | Columns: 17
                        null_count  null_percentage
AMT_ANNUITY                1226791            71.47
AMT_CREDIT_MAX_OVERDUE     1124488            65.51
DAYS_ENDDATE_FACT           633653            36.92
AMT_CREDIT_SUM_LIMIT        591780            34.48
AMT_CREDIT_SUM_DEBT         257669            15.01
DAYS_CREDIT_ENDDATE         105553             6.15
AMT_CREDIT_SUM                  13             0.00
./../data/raw/bureau_balance.csv

================================================================================
Table: bureau_balance.csv | Rows: 27,299,925 | Columns: 3
No null values found.
./../data/raw/credit_card_balance.csv

================================================================================
Table: credit_card_balance.csv | Rows: 3,840,312 | Columns: 23
                            null_count  null_percentage
AMT_PAYMENT_CURRENT             767988            20.00
AMT_DRAWINGS_ATM_CURRENT        749816            19.52
AMT_DRAWINGS_OTHER_CURRENT      749816            19.52
AMT_DRAWINGS_POS_CURRENT        749816            19.52
CNT_DRAWINGS_ATM_CURRENT        749816            19.52
CNT_DRAWINGS_POS_CURRENT        749816            19.52
CNT_DRAWINGS_OTHER_CURRENT      749816            19.52
AMT_INST_MIN_REGULARITY         305236             7.95
CNT_INSTALMENT_MATURE_CUM       305236             7.95
./../data/raw/installments_payments.csv

================================================================================
Table: installments_payments.csv | Rows: 13,605,401 | Columns: 8
                    null_count  null_percentage
DAYS_ENTRY_PAYMENT        2905             0.02
AMT_PAYMENT               2905             0.02
./../data/raw/previous_application.csv

================================================================================
Table: previous_application.csv | Rows: 1,670,214 | Columns: 37
                           null_count  null_percentage
RATE_INTEREST_PRIVILEGED      1664263            99.64
RATE_INTEREST_PRIMARY         1664263            99.64
AMT_DOWN_PAYMENT               895844            53.64
RATE_DOWN_PAYMENT              895844            53.64
NAME_TYPE_SUITE                820405            49.12
DAYS_LAST_DUE                  673065            40.30
DAYS_FIRST_DRAWING             673065            40.30
DAYS_FIRST_DUE                 673065            40.30
DAYS_TERMINATION               673065            40.30
NFLAG_INSURED_ON_APPROVAL      673065            40.30
DAYS_LAST_DUE_1ST_VERSION      673065            40.30
AMT_GOODS_PRICE                385515            23.08
AMT_ANNUITY                    372235            22.29
CNT_PAYMENT                    372230            22.29
PRODUCT_COMBINATION               346             0.02
AMT_CREDIT                          1             0.00

In [4]:
for file in files:
    df = pd.read_csv(os.path.join(data_dir, file))
    print("Dataframe shape : ", df.shape)
    for col in df.columns:
        print(col,end=)

SyntaxError: invalid syntax (2722058908.py, line 5)

In [5]:
df = pd.read_csv(os.path.join(data_dir, 'application_train.csv'))
for col  in df.columns:
    print(col," ",df[col].unique())
    print("\n######################\n")

SK_ID_CURR   [100002 100003 100004 ... 456253 456254 456255]

######################

TARGET   [1 0]

######################

NAME_CONTRACT_TYPE   ['Cash loans' 'Revolving loans']

######################

CODE_GENDER   ['M' 'F' 'XNA']

######################

FLAG_OWN_CAR   ['N' 'Y']

######################

FLAG_OWN_REALTY   ['Y' 'N']

######################

CNT_CHILDREN   [ 0  1  2  3  4  7  5  6  8  9 11 12 10 19 14]

######################

AMT_INCOME_TOTAL   [202500.  270000.   67500.  ...  96768.  546250.5 113062.5]

######################

AMT_CREDIT   [ 406597.5 1293502.5  135000.  ...  181989.   743863.5 1391130. ]

######################

AMT_ANNUITY   [24700.5 35698.5  6750.  ... 71986.5 58770.  77809.5]

######################

AMT_GOODS_PRICE   [ 351000.  1129500.   135000.  ...  453465.   143977.5  743863.5]

######################

NAME_TYPE_SUITE   ['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' nan
 'Other_B' 'Group of people']

######################

NAME_INCOME_TYPE   ['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']

######################

NAME_EDUCATION_TYPE   ['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']

######################

NAME_FAMILY_STATUS   ['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']

######################

NAME_HOUSING_TYPE   ['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']

######################

REGION_POPULATION_RELATIVE   [0.018801 0.003541 0.010032 0.008019 0.028663 0.035792 0.003122 0.018634
 0.019689 0.0228   0.015221 0.031329 0.016612 0.010006 0.020713 0.010966
 0.04622  0.025164 0.006296 0.026392 0.018029 0.019101 0.030755 0.008575
 0.01885  0.006207 0.009175 0.007305 0.007114 0.009334 0.022625 0.01452
 0.006629 0.00733  0.032561 0.00496  0.072508 0.009657 0.02461  0.003069
 0.020246 0.018209 0.009549 0.007274 0.002134 0.010276 0.003813 0.003818
 0.00712  0.0105   0.010147 0.010643 0.008866 0.00702  0.002506 0.005313
 0.006233 0.008474 0.005144 0.011657 0.008625 0.014464 0.004849 0.006008
 0.00963  0.005002 0.006852 0.011703 0.006305 0.010556 0.00823  0.006671
 0.002042 0.005084 0.008068 0.001333 0.001417 0.001276 0.000938 0.000533
 0.00029 ]

######################

DAYS_BIRTH   [ -9461 -16765 -19046 ...  -7951  -7857 -25061]

######################

DAYS_EMPLOYED   [  -637  -1188   -225 ... -12971 -11084  -8694]

######################

DAYS_REGISTRATION   [ -3648.  -1186.  -4260. ... -16396. -14558. -14798.]

######################

DAYS_ID_PUBLISH   [-2120  -291 -2531 ... -6194 -5854 -6211]

######################

OWN_CAR_AGE   [nan 26. 17.  8. 23.  7. 14.  1.  3. 13. 10.  2. 21. 20. 22. 65.  5. 11.
  9.  4. 15. 12. 25.  6. 64.  0. 27. 19. 28. 18. 16. 30. 36. 24. 39. 29.
 40. 41. 31. 42. 37. 35. 34. 33. 54. 38. 32. 43. 55. 49. 44. 63. 46. 45.
 48. 56. 51. 57. 69. 50. 47. 91. 52.]

######################

FLAG_MOBIL   [1 0]

######################

FLAG_EMP_PHONE   [1 0]

######################

FLAG_WORK_PHONE   [0 1]

######################

FLAG_CONT_MOBILE   [1 0]

######################

FLAG_PHONE   [1 0]

######################

FLAG_EMAIL   [0 1]

######################

OCCUPATION_TYPE   ['Laborers' 'Core staff' 'Accountants' 'Managers' nan 'Drivers'
 'Sales staff' 'Cleaning staff' 'Cooking staff' 'Private service staff'
 'Medicine staff' 'Security staff' 'High skill tech staff'
 'Waiters/barmen staff' 'Low-skill Laborers' 'Realty agents' 'Secretaries'
 'IT staff' 'HR staff']

######################

CNT_FAM_MEMBERS   [ 1.  2.  3.  4.  5.  6.  9.  7.  8. 10. 13. nan 14. 12. 20. 15. 16. 11.]

######################

REGION_RATING_CLIENT   [2 1 3]

######################

REGION_RATING_CLIENT_W_CITY   [2 1 3]

######################

WEEKDAY_APPR_PROCESS_START   ['WEDNESDAY' 'MONDAY' 'THURSDAY' 'SUNDAY' 'SATURDAY' 'FRIDAY' 'TUESDAY']

######################

HOUR_APPR_PROCESS_START   [10 11  9 17 16 14  8 15  7 13  6 12 19  3 18 21  4  5 20 22  1  2 23  0]

######################

REG_REGION_NOT_LIVE_REGION   [0 1]

######################

REG_REGION_NOT_WORK_REGION   [0 1]

######################

LIVE_REGION_NOT_WORK_REGION   [0 1]

######################

REG_CITY_NOT_LIVE_CITY   [0 1]

######################

REG_CITY_NOT_WORK_CITY   [0 1]

######################

LIVE_CITY_NOT_WORK_CITY   [0 1]

######################

ORGANIZATION_TYPE   ['Business Entity Type 3' 'School' 'Government' 'Religion' 'Other' 'XNA'
 'Electricity' 'Medicine' 'Business Entity Type 2' 'Self-employed'
 'Transport: type 2' 'Construction' 'Housing' 'Kindergarten'
 'Trade: type 7' 'Industry: type 11' 'Military' 'Services'
 'Security Ministries' 'Transport: type 4' 'Industry: type 1' 'Emergency'
 'Security' 'Trade: type 2' 'University' 'Transport: type 3' 'Police'
 'Business Entity Type 1' 'Postal' 'Industry: type 4' 'Agriculture'
 'Restaurant' 'Culture' 'Hotel' 'Industry: type 7' 'Trade: type 3'
 'Industry: type 3' 'Bank' 'Industry: type 9' 'Insurance' 'Trade: type 6'
 'Industry: type 2' 'Transport: type 1' 'Industry: type 12' 'Mobile'
 'Trade: type 1' 'Industry: type 5' 'Industry: type 10' 'Legal Services'
 'Advertising' 'Trade: type 5' 'Cleaning' 'Industry: type 13'
 'Trade: type 4' 'Telecom' 'Industry: type 8' 'Realtor' 'Industry: type 6']

######################

EXT_SOURCE_1   [0.08303697 0.31126731        nan ... 0.14557045 0.7440264  0.73445967]

######################

EXT_SOURCE_2   [0.26294859 0.62224578 0.55591208 ... 0.13118876 0.26448565 0.2678342 ]

######################

EXT_SOURCE_3   [1.39375780e-01            nan 7.29566691e-01 6.21226338e-01
 4.92060094e-01 5.40654450e-01 7.51723715e-01 3.63945239e-01
 6.52896552e-01 1.76652579e-01 7.70087070e-01 6.78567689e-01
 6.21030378e-02 5.56727426e-01 4.77649155e-01 5.42445144e-01
 3.58951229e-01 6.69056695e-01 5.65607981e-01 4.61482391e-01
 1.90705948e-01 6.59405532e-01 5.24496446e-01 4.10102573e-01
 7.98137231e-01 4.11848556e-01 7.54406173e-01 7.22392890e-01
 6.05836265e-01 3.20163367e-01 3.99675616e-01 6.84827659e-01
 4.75849909e-01 7.28141299e-01 4.66864006e-01 4.79448981e-01
 3.09275356e-01 7.99296783e-01 7.01695774e-01 7.38019620e-01
 7.01088438e-02 1.69428727e-01 5.13693766e-01 7.07699345e-01
 3.39287700e-01 6.97146908e-01 4.34733249e-01 2.34015167e-01
 9.50703958e-02 5.62060483e-01 4.29423684e-01 4.13596760e-01
 8.32785025e-01 3.94495405e-01 5.97192427e-01 6.94092643e-01
 1.98620045e-01 1.91821602e-01 4.08358853e-01 5.35276250e-01
 4.52533559e-01 7.20944150e-01 6.44679455e-01 3.42528872e-01
 8.24594971e-01 5.11891802e-01 6.41368257e-01 3.28063161e-01
 2.28883417e-01 7.74985465e-02 7.89880347e-01 2.65049430e-01
 7.10551247e-02 1.21408286e-01 5.81483706e-01 4.06617437e-01
 6.73830078e-01 5.54946769e-01 5.74446617e-01 1.20641030e-01
 5.72682505e-01 9.63186928e-02 6.83268831e-01 7.39411754e-01
 7.55740050e-01 2.11550764e-01 9.20128094e-02 7.49021705e-01
 3.53987608e-01 7.46300213e-01 2.89611238e-01 3.17031779e-01
 2.32724776e-01 8.12822607e-01 1.56639827e-01 1.61463080e-01
 3.29655054e-01 8.16092360e-01 5.95456203e-01 4.17099668e-01
 6.75413291e-01 4.43615308e-01 4.20610964e-01 7.95803133e-01
 7.71361592e-01 5.19097338e-01 5.46023197e-01 7.88680775e-01
 5.22697317e-01 5.08286991e-01 1.92942228e-01 3.03146374e-01
 6.39707568e-01 2.76440695e-01 3.50695843e-01 2.69285800e-01
 5.44234741e-01 5.49596502e-01 5.93717587e-01 7.06205110e-01
 5.06484240e-01 7.44932185e-01 3.07736696e-01 4.27657370e-01
 3.37672722e-01 6.07557300e-01 7.36622698e-01 3.44155007e-01
 6.34705531e-01 2.97086612e-01 4.25892898e-01 7.59712182e-01
 1.80887978e-01 6.09275667e-01 7.16570245e-01 2.18859082e-01
 2.17628520e-01 6.54529280e-01 1.30947153e-01 3.80799683e-01
 4.54321060e-01 7.42181612e-01 2.43186480e-01 1.96333966e-01
 4.56109739e-01 7.30987370e-01 3.79100485e-01 5.20897599e-01
 2.70707387e-01 6.95621930e-01 7.13631400e-01 6.31354537e-01
 2.25086862e-01 4.48962273e-01 7.50375150e-01 1.83035167e-01
 8.00451340e-01 5.28092751e-01 6.22922000e-01 7.58393062e-01
 2.37916080e-01 3.31250865e-01 6.12704244e-01 4.63275328e-01
 5.88487788e-01 3.15472155e-01 2.00926088e-01 5.16817674e-02
 4.97468889e-01 4.38281374e-01 6.64248263e-01 4.95665829e-01
 6.89479143e-01 5.77969119e-01 2.10350229e-01 6.38043528e-01
 7.35220999e-01 6.29674251e-01 2.60855914e-01 4.70456116e-01
 7.78904039e-01 1.73527430e-01 5.37069958e-01 5.17296581e-01
 6.72242890e-01 6.00657537e-01 7.86266615e-01 2.63646813e-01
 4.31191798e-01 4.65069215e-01 3.06202298e-01 3.77404249e-01
 5.51381262e-01 6.57783800e-01 6.92559067e-01 7.40799088e-01
 1.15386662e-01 7.19490785e-01 8.02745476e-01 4.86653157e-01
 3.40906426e-01 2.23831317e-01 6.51260219e-01 7.12155155e-01
 3.84206813e-01 3.55638717e-01 3.89338792e-01 7.10674386e-01
 9.02209393e-02 5.27265239e-04 7.33814537e-01 7.85052026e-01
 3.87625344e-01 6.80138822e-01 6.36376171e-01 6.51096140e-02
 6.65854922e-01 6.81705878e-01 7.03203305e-01 1.87388765e-01
 6.62637792e-01 2.56705572e-01 6.33031641e-01 7.00183851e-01
 7.67523105e-01 3.74020803e-01 7.90596960e-02 7.75155267e-01
 6.98667555e-01 6.76992503e-01 3.49055251e-01 7.82607837e-01
 2.75000352e-01 2.66456808e-01 6.56158373e-01 5.86740009e-01
 5.33481630e-01 1.26100559e-01 3.85914672e-01 6.27990819e-01
 3.72333666e-01 3.96219572e-01 9.32250954e-02 7.73895694e-01
 1.44648146e-01 3.91054977e-01 2.83711883e-01 2.15182404e-01
 2.73564678e-01 5.29889834e-01 9.88592804e-02 2.52598698e-01
 4.01407414e-01 6.19527708e-01 7.66233670e-01 8.27702668e-01
 3.13916677e-01 5.98926218e-01 7.63639921e-01 3.70649632e-01
 5.34780874e-02 6.02386344e-01 1.50085176e-01 3.32850564e-01
 4.32961667e-01 6.70651753e-01 6.26304277e-01 5.63835049e-01
 5.15495375e-01 6.14414378e-01 6.43025564e-01 4.50747282e-01
 3.75711010e-01 2.88129600e-01 1.64414179e-01 6.10991328e-01
 1.47345918e-01 6.61023539e-01 4.83050188e-01 5.04681319e-01
 7.47663390e-01 7.72631135e-01 7.93449030e-01 1.88489534e-01
 5.47810466e-01 4.88455184e-01 8.34784159e-01 2.09154699e-01
 1.41991543e-01 8.10618022e-01 6.46329898e-01 3.26475210e-01
 6.16121691e-01 4.57899551e-01 8.21443313e-01 1.36800522e-01
 5.70916542e-01 3.97946322e-01 2.82248434e-01 4.93862882e-01
 5.60284328e-01 5.53164699e-01 1.26897526e-01 1.60488931e-01
 3.12365369e-01 5.67379237e-01 4.74051289e-01 5.01075160e-01
 7.24966768e-02 4.40057830e-01 4.24130311e-01 9.69483171e-02
 8.65895915e-01 4.99272015e-01 1.97474512e-01 4.45396242e-01
 1.25307878e-01 6.17826147e-01 1.74564266e-01 7.09189110e-01
 3.21735282e-01 2.26347396e-01 7.61026370e-01 3.45784802e-01
 1.67408447e-01 6.04112600e-01 5.83237926e-01 1.84116156e-01
 8.63363382e-01 7.92264474e-01 1.19877961e-01 5.76208836e-01
 8.03885061e-01 2.22580765e-01 3.65616507e-01 8.19317692e-01
 5.90233339e-01 5.38862707e-01 5.88259005e-02 8.35776516e-01
 3.68968738e-01 7.18032811e-01 4.68659655e-01 1.57594999e-01
 2.13966852e-01 1.30128543e-01 6.91021227e-01 5.20364071e-02
 1.35106016e-01 2.95582642e-01 1.45542813e-01 3.18595524e-01
 1.24519471e-01 7.62335618e-01 2.04422625e-01 5.26294940e-01
 7.80143638e-01 1.11756371e-01 5.31686143e-01 9.14119938e-02
 4.59690450e-01 4.84851475e-01 5.69148771e-01 8.59924176e-01
 6.49620311e-01 8.07273923e-01 7.64735192e-02 4.81249341e-01
 6.24614658e-01 7.15326763e-02 5.58506628e-01 2.30158897e-01
 1.53802586e-01 1.23735322e-01 8.05019662e-01 6.86382335e-01
 4.36506499e-01 5.10089528e-01 4.90257512e-01 1.41115100e-01
 1.03449052e-01 2.91097380e-01 4.22369652e-01 7.04706423e-01
 8.20382959e-01 8.06149281e-01 1.06155623e-01 1.85202082e-01
 2.27612915e-01 8.06495443e-02 2.85179905e-01 2.41861487e-01
 3.82501804e-01 7.39651461e-02 3.10818254e-01 1.37654462e-01
 6.04436913e-02 4.18854289e-01 2.55331771e-01 8.18247508e-01
 2.36610824e-01 1.05473186e-01 8.48244300e-01 2.79335321e-01
 8.28728832e-01 4.41835823e-01 9.26171714e-02 6.87932838e-01
 1.46442067e-01 2.48535557e-01 2.16402961e-01 2.03252114e-01
 7.68807573e-01 5.84990040e-01 6.47976860e-01 4.72253343e-01
 1.00151820e-01 5.91976618e-01 4.03141677e-01 8.33641977e-02
 2.98594990e-01 3.34454126e-01 1.52866229e-01 1.22955418e-01
 3.36061521e-01 8.43543539e-01 6.67457742e-01 1.51934549e-01
 3.01624892e-01 1.99770570e-01 2.49885063e-01 2.31439351e-01
 8.13917470e-01 1.40243184e-01 5.02878277e-01 2.40541417e-01
 1.59519540e-01 2.06778654e-01 7.25276435e-01 1.95198406e-01
 2.58084204e-01 1.27698794e-01 7.94628583e-01 2.53962809e-01
 1.43758053e-01 7.23836990e-01 8.61652750e-01 3.47418227e-01
 3.00107757e-01 1.35951044e-01 6.82511545e-02 3.60612566e-01
 7.76409851e-01 1.79821765e-01 2.47190938e-01 3.92773861e-01
 8.08393591e-01 1.11042402e-01 1.78760465e-01 4.47178578e-01
 7.15103102e-01 4.04878364e-01 3.57293268e-01 2.62248971e-01
 1.17613732e-01 9.56927242e-02 5.79727423e-01 2.21335206e-01
 3.62277247e-01 1.68416171e-01 7.83832434e-01 5.49573941e-02
 8.56412800e-01 2.67868936e-01 3.67291018e-01 7.32403323e-01
 1.72495467e-01 2.86652483e-01 2.80789574e-01 3.52339973e-01
 1.81959110e-01 1.00803706e-01 8.50326149e-02 2.35310517e-01
 1.55689375e-01 2.12756305e-01 1.34265424e-01 1.58554900e-01
 8.62510303e-01 3.04672184e-01 1.32597495e-01 6.77939106e-02
 7.53067392e-01 2.30618111e-02 3.23311245e-01 1.48254379e-01
 4.14716966e-02 1.14652494e-01 2.72133684e-01 2.94083101e-01
 8.73042707e-02 2.07964174e-01 1.04119916e-01 1.29314289e-01
 8.67312636e-02 1.66405546e-01 4.15347145e-01 8.81026575e-01
 1.86292950e-01 3.92377151e-02 4.79287862e-02 2.44516392e-01
 1.12474350e-01 2.39226279e-01 8.29750142e-01 8.78806992e-02
 1.65407460e-01 2.59467655e-01 2.51239446e-01 2.77885689e-01
 8.11722793e-01 8.38724852e-01 1.06841948e-01 1.38512877e-01
 7.26711209e-01 2.02086602e-01 4.82589835e-02 1.71468367e-01
 1.45563649e-02 7.43559314e-01 8.82530313e-01 1.09626434e-01
 8.11859432e-02 4.41303159e-02 1.08226323e-01 3.34404021e-02
 8.61616624e-02 8.40666560e-01 8.17255925e-02 1.63425695e-01
 8.22498762e-01 8.45437922e-01 2.05598139e-01 8.37746853e-01
 5.06315131e-02 6.29485767e-02 6.25244733e-02 8.23549312e-01
 2.20094645e-01 3.97851461e-02 5.45839935e-02 8.55523587e-01
 8.28147042e-02 1.31770133e-01 4.17593601e-02 8.52828467e-01
 3.24891229e-01 1.13196353e-01 7.85361446e-02 1.02782014e-01
 1.33429254e-01 1.54743631e-01 7.59656813e-02 1.41482655e-02
 1.01459357e-01 8.01600903e-01 1.19119065e-01 6.59932074e-02
 7.77659443e-01 1.89595260e-01 6.16842561e-02 1.02118788e-01
 1.10332428e-01 1.75605979e-01 7.29831557e-02 7.64939274e-01
 1.77704072e-01 2.45851214e-01 8.22685076e-02 8.39170037e-02
 1.70446123e-01 8.69210801e-01 8.84605647e-02 9.75816127e-02
 1.28504377e-01 5.42129844e-02 3.68624823e-02 5.68607395e-02
 5.96296575e-02 1.04794623e-01 2.38884361e-02 8.42589277e-01
 7.87476198e-01 9.82185953e-02 3.18464044e-02 7.05805188e-02
 7.57069015e-01 1.51007535e-01 8.33786999e-01 4.99426019e-02
 7.96972682e-01 2.92588007e-01 7.91074913e-01 1.94067828e-01
 8.09508289e-01 9.08147090e-02 8.46378063e-01 4.63097465e-02
 8.90438827e-02 8.39698085e-01 4.85913395e-02 6.91742267e-02
 1.49167461e-01 4.44355656e-02 1.22179744e-01 8.44731375e-02
 8.17172399e-01 1.16867266e-01 3.66072628e-02 8.01163805e-02
 8.25635745e-01 8.80268480e-01 2.63596859e-02 8.96306691e-02
 6.87112549e-02 7.49592809e-02 4.06200396e-02 6.38048445e-02
 8.85488394e-01 5.09793334e-02 5.60920788e-02 1.18364326e-01
 7.20131886e-02 6.68879340e-02 3.27480398e-02 1.42872523e-01
 6.46719559e-02 7.95864362e-02 1.08924404e-01 8.47313519e-01
 1.07532176e-01 9.95036835e-02 7.69844691e-02 6.73395087e-02
 8.59053129e-01 7.80157665e-02 8.36764077e-01 5.53331995e-02
 3.89667159e-02 3.53564629e-02 5.64751797e-02 6.96400847e-02
 6.12681138e-02 1.13922396e-01 7.81378238e-01 4.72748180e-02
 9.38365970e-02 8.66731234e-01 8.51008703e-01 5.27525967e-02
 9.44516920e-02 8.55954513e-02 8.31778230e-01 6.55500263e-02
 1.16124914e-01 6.08545970e-02 5.80323088e-02 3.71194126e-02
 5.84278409e-02 6.64391717e-02 1.94675368e-02 2.88760241e-02
 2.80779003e-02 1.62441998e-01 6.33753623e-02 2.61752069e-02
 5.38443535e-02 5.76392903e-02 3.63537437e-02 6.42370375e-02
 3.46258510e-02 6.00353829e-02 7.44606879e-02 3.41468857e-02
 1.60781171e-02 8.57297454e-01 7.34726404e-02 2.43982125e-02
 3.76384476e-02 5.31141728e-02 8.54629801e-01 5.02859402e-02
 4.89258668e-02 5.13294139e-02 2.69207441e-02 2.67324463e-02
 3.20695369e-02 8.53731432e-01 3.51112903e-02 3.86975129e-02
 3.95105215e-02 5.72487718e-02 3.29772745e-02 4.92625778e-02
 8.79506216e-01 8.96009549e-01 8.65056176e-01 8.30766606e-01
 5.23933458e-02 2.82753998e-02 8.74844253e-01 4.26338431e-02
 8.78739767e-01 4.03398941e-02 3.05388193e-02 4.69510224e-02
 3.32080587e-02 3.25203451e-02 4.66293360e-02 3.61019144e-02
 4.53634379e-02 8.50091881e-01 4.56768096e-02 8.77194258e-01
 4.09020477e-02 3.16247736e-02 4.38270669e-02 4.11859296e-02
 2.65454297e-02 4.96014853e-02 4.23404218e-02 4.76007352e-02
 2.84742479e-02 8.70841988e-01 7.54609403e-02 8.15007386e-01
 3.11859799e-02 3.39098058e-02 2.50944406e-02 1.67772514e-02
 2.74934071e-02 3.56032843e-02 4.59922418e-02 4.20489313e-02
 2.96961417e-02 2.58100107e-02 5.92265014e-02 4.47428279e-02
 1.90587694e-02 8.73256255e-01 3.81644526e-02 3.58517647e-02
 5.57114233e-02 4.29292066e-02 8.49170417e-01 2.47439401e-02
 8.41630287e-01 8.26671642e-01 8.58177559e-01 3.73780642e-02
 8.64212002e-01 8.87664202e-01 3.09687983e-02 2.37208308e-02
 4.35258068e-02 3.14046353e-02 3.79005735e-02 3.48677564e-02
 2.49185898e-02 3.22941806e-02 3.01146246e-02 4.50521147e-02
 2.04550299e-02 1.13457194e-02 4.00616000e-02 1.70168720e-02
 2.40571964e-02 2.27390386e-02 2.01679886e-02 2.86744531e-02
 2.52715002e-02 3.03260035e-02 2.14915157e-02 2.94890196e-02
 3.84300954e-02 3.07530812e-02 2.99046737e-02 2.24206800e-02
 3.43855641e-02 2.03110127e-02 8.72455816e-01 2.73012161e-02
 2.19512925e-02 2.71103313e-02 8.71651065e-01 2.54497765e-02
 1.27159239e-02 8.93976075e-01 2.42271194e-02 2.35543731e-02
 1.86584217e-02 2.32248707e-02 1.82663270e-02 2.59919845e-02
 2.92832986e-02 1.39484656e-02 8.44493084e-01 1.75062455e-02
 2.78817406e-02 1.65409482e-02 1.89243929e-02 2.90789697e-02
 1.81374345e-02 2.00259511e-02 4.32265239e-02]

######################

APARTMENTS_AVG   [0.0247 0.0959    nan ... 0.0261 0.0731 0.3466]

######################

BASEMENTAREA_AVG   [0.0369 0.0529    nan ... 0.274  0.2733 0.636 ]

######################

YEARS_BEGINEXPLUATATION_AVG   [0.9722 0.9851    nan 0.9811 0.9806 0.9985 0.9881 0.9781 0.9786 0.9876
 0.9861 0.9732 0.9831 0.9697 0.9901 0.9801 0.9762 0.996  0.998  0.9846
 0.9886 0.9354 0.9841 0.9856 0.9955 0.9677 0.9891 0.9752 0.9826 0.9727
 0.6508 0.9578 0.9742 0.9707 0.9975 0.999  0.9816 0.9866 0.9836 0.994
 0.9757 0.9737 0.9791 0.9821 0.9682 0.995  0.9771 0.9945 0.9747 0.9776
 0.9796 0.9896 0.9692 0.9518 0.9995 0.9414 0.993  0.9702 0.9921 0.9916
 0.9712 0.4933 0.9871 0.9672 0.9911 0.9608 0.9906 0.9503 0.9598 0.997
 0.9583 0.9767 0.929  0.9935 0.9617 0.9563 0.9965 0.9925 0.9508 0.9717
 0.9687 0.9667 0.9359 0.9573 0.9588 0.9513 0.9642 0.9553 0.9603 0.9543
 0.9622 0.9637 0.3224 0.9568 0.6538 0.9652 0.9523 0.4953 0.9473 0.
 0.9071 0.9593 0.9627 0.9613 0.9439 0.9434 0.9488 0.4973 0.9459 0.9334
 0.9657 0.9632 0.9424 0.9548 0.9449 0.4913 0.9647 0.9662 0.9468 0.3284
 0.9001 0.9324 0.9389 1.     0.9493 0.9463 0.9498 0.92   0.4903 0.9121
 0.9444 0.3259 0.9409 0.9384 0.4848 0.9329 0.9429 0.928  0.9483 0.9478
 0.9538 0.9379 0.9404 0.4759 0.8977 0.7442 0.927  0.9528 0.8927 0.9344
 0.3279 0.9275 0.9056 0.9558 0.4983 0.4883 0.9339 0.7432 0.7829 0.6533
 0.9136 0.1987 0.9195 0.9419 0.9319 0.9175 0.5315 0.9309 0.9305 0.9349
 0.6841 0.9399 0.9066 0.926  0.4943 0.9394 0.9245 0.3294 0.9295 0.8674
 0.229  0.8579 0.5852 0.4863 0.9454 0.93   0.9235 0.916  0.9314 0.9369
 0.924  0.6513 0.3304 0.8877 0.8922 0.3289 0.921  0.9106 0.9533 0.3254
 0.4779 0.9151 0.4978 0.4898 0.7914 0.4893 0.0979 0.6344 0.5857 0.9374
 0.9096 0.4938 0.918  0.8967 0.4918 0.4853 0.7437 0.925  0.9225 0.6577
 0.923  0.9215 0.8276 0.6567 0.6547 0.8992 0.2434 0.9364 0.1942 0.4968

In [20]:
df.head(20)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.00,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.00,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
5,215354,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.00,71017.38,108982.62,0.0,Credit card,-31,NaN
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.0,0,42103.80,42103.80,0.00,0.0,Consumer credit,-22,NaN
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.0,0,76878.45,0.00,0.00,0.0,Consumer credit,-1710,NaN
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.0,0,103007.70,0.00,0.00,0.0,Consumer credit,-840,NaN
9,162297,5714471,Active,currency 1,-1146,0,-484.0,NaN,0.0,0,4500.00,0.00,0.00,0.0,Credit card,-690,NaN
10,162297,5714472,Active,currency 1,-1146,0,-180.0,NaN,0.0,0,337500.00,0.00,0.00,0.0,Credit card,-690,NaN
11,162297,5714473,Closed,currency 1,-2456,0,-629.0,-825.0,NaN,0,675000.00,0.00,0.00,0.0,Consumer credit,-706,NaN
12,162297,5714474,Active,currency 1,-277,0,5261.0,NaN,0.0,0,7033500.00,NaN,NaN,0.0,Mortgage,-31,NaN
13,402440,5714475,Active,currency 1,-96,0,269.0,NaN,0.0,0,89910.00,76905.00,0.00,0.0,Consumer credit,-22,NaN
14,238881,5714482,Closed,currency 1,-318,0,-187.0,-187.0,NaN,0,0.00,0.00,0.00,0.0,Credit card,-185,NaN
15,238881,5714484,Closed,currency 1,-2911,0,-2607.0,-2604.0,NaN,0,48555.00,NaN,NaN,0.0,Consumer credit,-2601,NaN
16,238881,5714485,Closed,currency 1,-2148,0,-1595.0,-987.0,NaN,0,135000.00,NaN,NaN,0.0,Consumer credit,-984,NaN
17,238881,5714486,Active,currency 1,-381,0,NaN,NaN,NaN,0,450000.00,520920.00,NaN,0.0,Consumer credit,-4,NaN
18,238881,5714487,Active,currency 1,-95,0,1720.0,NaN,NaN,0,67500.00,8131.50,NaN,0.0,Credit card,-7,NaN
19,238881,5714488,Closed,currency 1,-444,0,-77.0,-77.0,0.0,0,107184.06,0.00,0.00,0.0,Consumer credit,-71,NaN

In [ ]:
df[df["SK_ID_BUREAU"] == 5714466]

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [26]:
df = pd.read_csv(os.path.join(data_dir, 'bureau_balance.csv'))
df.head(20)

    SK_ID_BUREAU  MONTHS_BALANCE STATUS
0        5715448               0      C
1        5715448              -1      C
2        5715448              -2      C
3        5715448              -3      C
4        5715448              -4      C
5        5715448              -5      C
6        5715448              -6      C
7        5715448              -7      C
8        5715448              -8      C
9        5715448              -9      0
10       5715448             -10      0
11       5715448             -11      X
12       5715448             -12      X
13       5715448             -13      X
14       5715448             -14      0
15       5715448             -15      0
16       5715448             -16      0
17       5715448             -17      0
18       5715448             -18      0
19       5715448             -19      0

In [6]:
col_path = "application_train.csv"
df = pd.read_csv(os.path.join(data_dir, col_path))
df.head(20)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0

In [10]:
col_path = "application_train.csv"

df = pd.read_csv(os.path.join(data_dir, col_path))
for col  in df.columns:
    print(col," ",df[col].unique())
    print("\n######################\n")

SK_ID_CURR   [100002 100003 100004 ... 456253 456254 456255]

######################

TARGET   [1 0]

######################

NAME_CONTRACT_TYPE   ['Cash loans' 'Revolving loans']

######################

CODE_GENDER   ['M' 'F' 'XNA']

######################

FLAG_OWN_CAR   ['N' 'Y']

######################

FLAG_OWN_REALTY   ['Y' 'N']

######################

CNT_CHILDREN   [ 0  1  2  3  4  7  5  6  8  9 11 12 10 19 14]

######################

AMT_INCOME_TOTAL   [202500.  270000.   67500.  ...  96768.  546250.5 113062.5]

######################

AMT_CREDIT   [ 406597.5 1293502.5  135000.  ...  181989.   743863.5 1391130. ]

######################

AMT_ANNUITY   [24700.5 35698.5  6750.  ... 71986.5 58770.  77809.5]

######################

AMT_GOODS_PRICE   [ 351000.  1129500.   135000.  ...  453465.   143977.5  743863.5]

######################

NAME_TYPE_SUITE   ['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' nan
 'Other_B' 'Group of people']

######################

NAME_INCOME_TYPE   ['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']

######################

NAME_EDUCATION_TYPE   ['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']

######################

NAME_FAMILY_STATUS   ['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']

######################

NAME_HOUSING_TYPE   ['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']

######################

REGION_POPULATION_RELATIVE   [0.018801 0.003541 0.010032 0.008019 0.028663 0.035792 0.003122 0.018634
 0.019689 0.0228   0.015221 0.031329 0.016612 0.010006 0.020713 0.010966
 0.04622  0.025164 0.006296 0.026392 0.018029 0.019101 0.030755 0.008575
 0.01885  0.006207 0.009175 0.007305 0.007114 0.009334 0.022625 0.01452
 0.006629 0.00733  0.032561 0.00496  0.072508 0.009657 0.02461  0.003069
 0.020246 0.018209 0.009549 0.007274 0.002134 0.010276 0.003813 0.003818
 0.00712  0.0105   0.010147 0.010643 0.008866 0.00702  0.002506 0.005313
 0.006233 0.008474 0.005144 0.011657 0.008625 0.014464 0.004849 0.006008
 0.00963  0.005002 0.006852 0.011703 0.006305 0.010556 0.00823  0.006671
 0.002042 0.005084 0.008068 0.001333 0.001417 0.001276 0.000938 0.000533
 0.00029 ]

######################

DAYS_BIRTH   [ -9461 -16765 -19046 ...  -7951  -7857 -25061]

######################

DAYS_EMPLOYED   [  -637  -1188   -225 ... -12971 -11084  -8694]

######################

DAYS_REGISTRATION   [ -3648.  -1186.  -4260. ... -16396. -14558. -14798.]

######################

DAYS_ID_PUBLISH   [-2120  -291 -2531 ... -6194 -5854 -6211]

######################

OWN_CAR_AGE   [nan 26. 17.  8. 23.  7. 14.  1.  3. 13. 10.  2. 21. 20. 22. 65.  5. 11.
  9.  4. 15. 12. 25.  6. 64.  0. 27. 19. 28. 18. 16. 30. 36. 24. 39. 29.
 40. 41. 31. 42. 37. 35. 34. 33. 54. 38. 32. 43. 55. 49. 44. 63. 46. 45.
 48. 56. 51. 57. 69. 50. 47. 91. 52.]

######################

FLAG_MOBIL   [1 0]

######################

FLAG_EMP_PHONE   [1 0]

######################

FLAG_WORK_PHONE   [0 1]

######################

FLAG_CONT_MOBILE   [1 0]

######################

FLAG_PHONE   [1 0]

######################

FLAG_EMAIL   [0 1]

######################

OCCUPATION_TYPE   ['Laborers' 'Core staff' 'Accountants' 'Managers' nan 'Drivers'
 'Sales staff' 'Cleaning staff' 'Cooking staff' 'Private service staff'
 'Medicine staff' 'Security staff' 'High skill tech staff'
 'Waiters/barmen staff' 'Low-skill Laborers' 'Realty agents' 'Secretaries'
 'IT staff' 'HR staff']

######################

CNT_FAM_MEMBERS   [ 1.  2.  3.  4.  5.  6.  9.  7.  8. 10. 13. nan 14. 12. 20. 15. 16. 11.]

######################

REGION_RATING_CLIENT   [2 1 3]

######################

REGION_RATING_CLIENT_W_CITY   [2 1 3]

######################

WEEKDAY_APPR_PROCESS_START   ['WEDNESDAY' 'MONDAY' 'THURSDAY' 'SUNDAY' 'SATURDAY' 'FRIDAY' 'TUESDAY']

######################

HOUR_APPR_PROCESS_START   [10 11  9 17 16 14  8 15  7 13  6 12 19  3 18 21  4  5 20 22  1  2 23  0]

######################

REG_REGION_NOT_LIVE_REGION   [0 1]

######################

REG_REGION_NOT_WORK_REGION   [0 1]

######################

LIVE_REGION_NOT_WORK_REGION   [0 1]

######################

REG_CITY_NOT_LIVE_CITY   [0 1]

######################

REG_CITY_NOT_WORK_CITY   [0 1]

######################

LIVE_CITY_NOT_WORK_CITY   [0 1]

######################

ORGANIZATION_TYPE   ['Business Entity Type 3' 'School' 'Government' 'Religion' 'Other' 'XNA'
 'Electricity' 'Medicine' 'Business Entity Type 2' 'Self-employed'
 'Transport: type 2' 'Construction' 'Housing' 'Kindergarten'
 'Trade: type 7' 'Industry: type 11' 'Military' 'Services'
 'Security Ministries' 'Transport: type 4' 'Industry: type 1' 'Emergency'
 'Security' 'Trade: type 2' 'University' 'Transport: type 3' 'Police'
 'Business Entity Type 1' 'Postal' 'Industry: type 4' 'Agriculture'
 'Restaurant' 'Culture' 'Hotel' 'Industry: type 7' 'Trade: type 3'
 'Industry: type 3' 'Bank' 'Industry: type 9' 'Insurance' 'Trade: type 6'
 'Industry: type 2' 'Transport: type 1' 'Industry: type 12' 'Mobile'
 'Trade: type 1' 'Industry: type 5' 'Industry: type 10' 'Legal Services'
 'Advertising' 'Trade: type 5' 'Cleaning' 'Industry: type 13'
 'Trade: type 4' 'Telecom' 'Industry: type 8' 'Realtor' 'Industry: type 6']

######################

EXT_SOURCE_1   [0.08303697 0.31126731        nan ... 0.14557045 0.7440264  0.73445967]

######################

EXT_SOURCE_2   [0.26294859 0.62224578 0.55591208 ... 0.13118876 0.26448565 0.2678342 ]

######################

EXT_SOURCE_3   [1.39375780e-01            nan 7.29566691e-01 6.21226338e-01
 4.92060094e-01 5.40654450e-01 7.51723715e-01 3.63945239e-01
 6.52896552e-01 1.76652579e-01 7.70087070e-01 6.78567689e-01
 6.21030378e-02 5.56727426e-01 4.77649155e-01 5.42445144e-01
 3.58951229e-01 6.69056695e-01 5.65607981e-01 4.61482391e-01
 1.90705948e-01 6.59405532e-01 5.24496446e-01 4.10102573e-01
 7.98137231e-01 4.11848556e-01 7.54406173e-01 7.22392890e-01
 6.05836265e-01 3.20163367e-01 3.99675616e-01 6.84827659e-01
 4.75849909e-01 7.28141299e-01 4.66864006e-01 4.79448981e-01
 3.09275356e-01 7.99296783e-01 7.01695774e-01 7.38019620e-01
 7.01088438e-02 1.69428727e-01 5.13693766e-01 7.07699345e-01
 3.39287700e-01 6.97146908e-01 4.34733249e-01 2.34015167e-01
 9.50703958e-02 5.62060483e-01 4.29423684e-01 4.13596760e-01
 8.32785025e-01 3.94495405e-01 5.97192427e-01 6.94092643e-01
 1.98620045e-01 1.91821602e-01 4.08358853e-01 5.35276250e-01
 4.52533559e-01 7.20944150e-01 6.44679455e-01 3.42528872e-01
 8.24594971e-01 5.11891802e-01 6.41368257e-01 3.28063161e-01
 2.28883417e-01 7.74985465e-02 7.89880347e-01 2.65049430e-01
 7.10551247e-02 1.21408286e-01 5.81483706e-01 4.06617437e-01
 6.73830078e-01 5.54946769e-01 5.74446617e-01 1.20641030e-01
 5.72682505e-01 9.63186928e-02 6.83268831e-01 7.39411754e-01
 7.55740050e-01 2.11550764e-01 9.20128094e-02 7.49021705e-01
 3.53987608e-01 7.46300213e-01 2.89611238e-01 3.17031779e-01
 2.32724776e-01 8.12822607e-01 1.56639827e-01 1.61463080e-01
 3.29655054e-01 8.16092360e-01 5.95456203e-01 4.17099668e-01
 6.75413291e-01 4.43615308e-01 4.20610964e-01 7.95803133e-01
 7.71361592e-01 5.19097338e-01 5.46023197e-01 7.88680775e-01
 5.22697317e-01 5.08286991e-01 1.92942228e-01 3.03146374e-01
 6.39707568e-01 2.76440695e-01 3.50695843e-01 2.69285800e-01
 5.44234741e-01 5.49596502e-01 5.93717587e-01 7.06205110e-01
 5.06484240e-01 7.44932185e-01 3.07736696e-01 4.27657370e-01
 3.37672722e-01 6.07557300e-01 7.36622698e-01 3.44155007e-01
 6.34705531e-01 2.97086612e-01 4.25892898e-01 7.59712182e-01
 1.80887978e-01 6.09275667e-01 7.16570245e-01 2.18859082e-01
 2.17628520e-01 6.54529280e-01 1.30947153e-01 3.80799683e-01
 4.54321060e-01 7.42181612e-01 2.43186480e-01 1.96333966e-01
 4.56109739e-01 7.30987370e-01 3.79100485e-01 5.20897599e-01
 2.70707387e-01 6.95621930e-01 7.13631400e-01 6.31354537e-01
 2.25086862e-01 4.48962273e-01 7.50375150e-01 1.83035167e-01
 8.00451340e-01 5.28092751e-01 6.22922000e-01 7.58393062e-01
 2.37916080e-01 3.31250865e-01 6.12704244e-01 4.63275328e-01
 5.88487788e-01 3.15472155e-01 2.00926088e-01 5.16817674e-02
 4.97468889e-01 4.38281374e-01 6.64248263e-01 4.95665829e-01
 6.89479143e-01 5.77969119e-01 2.10350229e-01 6.38043528e-01
 7.35220999e-01 6.29674251e-01 2.60855914e-01 4.70456116e-01
 7.78904039e-01 1.73527430e-01 5.37069958e-01 5.17296581e-01
 6.72242890e-01 6.00657537e-01 7.86266615e-01 2.63646813e-01
 4.31191798e-01 4.65069215e-01 3.06202298e-01 3.77404249e-01
 5.51381262e-01 6.57783800e-01 6.92559067e-01 7.40799088e-01
 1.15386662e-01 7.19490785e-01 8.02745476e-01 4.86653157e-01
 3.40906426e-01 2.23831317e-01 6.51260219e-01 7.12155155e-01
 3.84206813e-01 3.55638717e-01 3.89338792e-01 7.10674386e-01
 9.02209393e-02 5.27265239e-04 7.33814537e-01 7.85052026e-01
 3.87625344e-01 6.80138822e-01 6.36376171e-01 6.51096140e-02
 6.65854922e-01 6.81705878e-01 7.03203305e-01 1.87388765e-01
 6.62637792e-01 2.56705572e-01 6.33031641e-01 7.00183851e-01
 7.67523105e-01 3.74020803e-01 7.90596960e-02 7.75155267e-01
 6.98667555e-01 6.76992503e-01 3.49055251e-01 7.82607837e-01
 2.75000352e-01 2.66456808e-01 6.56158373e-01 5.86740009e-01
 5.33481630e-01 1.26100559e-01 3.85914672e-01 6.27990819e-01
 3.72333666e-01 3.96219572e-01 9.32250954e-02 7.73895694e-01
 1.44648146e-01 3.91054977e-01 2.83711883e-01 2.15182404e-01
 2.73564678e-01 5.29889834e-01 9.88592804e-02 2.52598698e-01
 4.01407414e-01 6.19527708e-01 7.66233670e-01 8.27702668e-01
 3.13916677e-01 5.98926218e-01 7.63639921e-01 3.70649632e-01
 5.34780874e-02 6.02386344e-01 1.50085176e-01 3.32850564e-01
 4.32961667e-01 6.70651753e-01 6.26304277e-01 5.63835049e-01
 5.15495375e-01 6.14414378e-01 6.43025564e-01 4.50747282e-01
 3.75711010e-01 2.88129600e-01 1.64414179e-01 6.10991328e-01
 1.47345918e-01 6.61023539e-01 4.83050188e-01 5.04681319e-01
 7.47663390e-01 7.72631135e-01 7.93449030e-01 1.88489534e-01
 5.47810466e-01 4.88455184e-01 8.34784159e-01 2.09154699e-01
 1.41991543e-01 8.10618022e-01 6.46329898e-01 3.26475210e-01
 6.16121691e-01 4.57899551e-01 8.21443313e-01 1.36800522e-01
 5.70916542e-01 3.97946322e-01 2.82248434e-01 4.93862882e-01
 5.60284328e-01 5.53164699e-01 1.26897526e-01 1.60488931e-01
 3.12365369e-01 5.67379237e-01 4.74051289e-01 5.01075160e-01
 7.24966768e-02 4.40057830e-01 4.24130311e-01 9.69483171e-02
 8.65895915e-01 4.99272015e-01 1.97474512e-01 4.45396242e-01
 1.25307878e-01 6.17826147e-01 1.74564266e-01 7.09189110e-01
 3.21735282e-01 2.26347396e-01 7.61026370e-01 3.45784802e-01
 1.67408447e-01 6.04112600e-01 5.83237926e-01 1.84116156e-01
 8.63363382e-01 7.92264474e-01 1.19877961e-01 5.76208836e-01
 8.03885061e-01 2.22580765e-01 3.65616507e-01 8.19317692e-01
 5.90233339e-01 5.38862707e-01 5.88259005e-02 8.35776516e-01
 3.68968738e-01 7.18032811e-01 4.68659655e-01 1.57594999e-01
 2.13966852e-01 1.30128543e-01 6.91021227e-01 5.20364071e-02
 1.35106016e-01 2.95582642e-01 1.45542813e-01 3.18595524e-01
 1.24519471e-01 7.62335618e-01 2.04422625e-01 5.26294940e-01
 7.80143638e-01 1.11756371e-01 5.31686143e-01 9.14119938e-02
 4.59690450e-01 4.84851475e-01 5.69148771e-01 8.59924176e-01
 6.49620311e-01 8.07273923e-01 7.64735192e-02 4.81249341e-01
 6.24614658e-01 7.15326763e-02 5.58506628e-01 2.30158897e-01
 1.53802586e-01 1.23735322e-01 8.05019662e-01 6.86382335e-01
 4.36506499e-01 5.10089528e-01 4.90257512e-01 1.41115100e-01
 1.03449052e-01 2.91097380e-01 4.22369652e-01 7.04706423e-01
 8.20382959e-01 8.06149281e-01 1.06155623e-01 1.85202082e-01
 2.27612915e-01 8.06495443e-02 2.85179905e-01 2.41861487e-01
 3.82501804e-01 7.39651461e-02 3.10818254e-01 1.37654462e-01
 6.04436913e-02 4.18854289e-01 2.55331771e-01 8.18247508e-01
 2.36610824e-01 1.05473186e-01 8.48244300e-01 2.79335321e-01
 8.28728832e-01 4.41835823e-01 9.26171714e-02 6.87932838e-01
 1.46442067e-01 2.48535557e-01 2.16402961e-01 2.03252114e-01
 7.68807573e-01 5.84990040e-01 6.47976860e-01 4.72253343e-01
 1.00151820e-01 5.91976618e-01 4.03141677e-01 8.33641977e-02
 2.98594990e-01 3.34454126e-01 1.52866229e-01 1.22955418e-01
 3.36061521e-01 8.43543539e-01 6.67457742e-01 1.51934549e-01
 3.01624892e-01 1.99770570e-01 2.49885063e-01 2.31439351e-01
 8.13917470e-01 1.40243184e-01 5.02878277e-01 2.40541417e-01
 1.59519540e-01 2.06778654e-01 7.25276435e-01 1.95198406e-01
 2.58084204e-01 1.27698794e-01 7.94628583e-01 2.53962809e-01
 1.43758053e-01 7.23836990e-01 8.61652750e-01 3.47418227e-01
 3.00107757e-01 1.35951044e-01 6.82511545e-02 3.60612566e-01
 7.76409851e-01 1.79821765e-01 2.47190938e-01 3.92773861e-01
 8.08393591e-01 1.11042402e-01 1.78760465e-01 4.47178578e-01
 7.15103102e-01 4.04878364e-01 3.57293268e-01 2.62248971e-01
 1.17613732e-01 9.56927242e-02 5.79727423e-01 2.21335206e-01
 3.62277247e-01 1.68416171e-01 7.83832434e-01 5.49573941e-02
 8.56412800e-01 2.67868936e-01 3.67291018e-01 7.32403323e-01
 1.72495467e-01 2.86652483e-01 2.80789574e-01 3.52339973e-01
 1.81959110e-01 1.00803706e-01 8.50326149e-02 2.35310517e-01
 1.55689375e-01 2.12756305e-01 1.34265424e-01 1.58554900e-01
 8.62510303e-01 3.04672184e-01 1.32597495e-01 6.77939106e-02
 7.53067392e-01 2.30618111e-02 3.23311245e-01 1.48254379e-01
 4.14716966e-02 1.14652494e-01 2.72133684e-01 2.94083101e-01
 8.73042707e-02 2.07964174e-01 1.04119916e-01 1.29314289e-01
 8.67312636e-02 1.66405546e-01 4.15347145e-01 8.81026575e-01
 1.86292950e-01 3.92377151e-02 4.79287862e-02 2.44516392e-01
 1.12474350e-01 2.39226279e-01 8.29750142e-01 8.78806992e-02
 1.65407460e-01 2.59467655e-01 2.51239446e-01 2.77885689e-01
 8.11722793e-01 8.38724852e-01 1.06841948e-01 1.38512877e-01
 7.26711209e-01 2.02086602e-01 4.82589835e-02 1.71468367e-01
 1.45563649e-02 7.43559314e-01 8.82530313e-01 1.09626434e-01
 8.11859432e-02 4.41303159e-02 1.08226323e-01 3.34404021e-02
 8.61616624e-02 8.40666560e-01 8.17255925e-02 1.63425695e-01
 8.22498762e-01 8.45437922e-01 2.05598139e-01 8.37746853e-01
 5.06315131e-02 6.29485767e-02 6.25244733e-02 8.23549312e-01
 2.20094645e-01 3.97851461e-02 5.45839935e-02 8.55523587e-01
 8.28147042e-02 1.31770133e-01 4.17593601e-02 8.52828467e-01
 3.24891229e-01 1.13196353e-01 7.85361446e-02 1.02782014e-01
 1.33429254e-01 1.54743631e-01 7.59656813e-02 1.41482655e-02
 1.01459357e-01 8.01600903e-01 1.19119065e-01 6.59932074e-02
 7.77659443e-01 1.89595260e-01 6.16842561e-02 1.02118788e-01
 1.10332428e-01 1.75605979e-01 7.29831557e-02 7.64939274e-01
 1.77704072e-01 2.45851214e-01 8.22685076e-02 8.39170037e-02
 1.70446123e-01 8.69210801e-01 8.84605647e-02 9.75816127e-02
 1.28504377e-01 5.42129844e-02 3.68624823e-02 5.68607395e-02
 5.96296575e-02 1.04794623e-01 2.38884361e-02 8.42589277e-01
 7.87476198e-01 9.82185953e-02 3.18464044e-02 7.05805188e-02
 7.57069015e-01 1.51007535e-01 8.33786999e-01 4.99426019e-02
 7.96972682e-01 2.92588007e-01 7.91074913e-01 1.94067828e-01
 8.09508289e-01 9.08147090e-02 8.46378063e-01 4.63097465e-02
 8.90438827e-02 8.39698085e-01 4.85913395e-02 6.91742267e-02
 1.49167461e-01 4.44355656e-02 1.22179744e-01 8.44731375e-02
 8.17172399e-01 1.16867266e-01 3.66072628e-02 8.01163805e-02
 8.25635745e-01 8.80268480e-01 2.63596859e-02 8.96306691e-02
 6.87112549e-02 7.49592809e-02 4.06200396e-02 6.38048445e-02
 8.85488394e-01 5.09793334e-02 5.60920788e-02 1.18364326e-01
 7.20131886e-02 6.68879340e-02 3.27480398e-02 1.42872523e-01
 6.46719559e-02 7.95864362e-02 1.08924404e-01 8.47313519e-01
 1.07532176e-01 9.95036835e-02 7.69844691e-02 6.73395087e-02
 8.59053129e-01 7.80157665e-02 8.36764077e-01 5.53331995e-02
 3.89667159e-02 3.53564629e-02 5.64751797e-02 6.96400847e-02
 6.12681138e-02 1.13922396e-01 7.81378238e-01 4.72748180e-02
 9.38365970e-02 8.66731234e-01 8.51008703e-01 5.27525967e-02
 9.44516920e-02 8.55954513e-02 8.31778230e-01 6.55500263e-02
 1.16124914e-01 6.08545970e-02 5.80323088e-02 3.71194126e-02
 5.84278409e-02 6.64391717e-02 1.94675368e-02 2.88760241e-02
 2.80779003e-02 1.62441998e-01 6.33753623e-02 2.61752069e-02
 5.38443535e-02 5.76392903e-02 3.63537437e-02 6.42370375e-02
 3.46258510e-02 6.00353829e-02 7.44606879e-02 3.41468857e-02
 1.60781171e-02 8.57297454e-01 7.34726404e-02 2.43982125e-02
 3.76384476e-02 5.31141728e-02 8.54629801e-01 5.02859402e-02
 4.89258668e-02 5.13294139e-02 2.69207441e-02 2.67324463e-02
 3.20695369e-02 8.53731432e-01 3.51112903e-02 3.86975129e-02
 3.95105215e-02 5.72487718e-02 3.29772745e-02 4.92625778e-02
 8.79506216e-01 8.96009549e-01 8.65056176e-01 8.30766606e-01
 5.23933458e-02 2.82753998e-02 8.74844253e-01 4.26338431e-02
 8.78739767e-01 4.03398941e-02 3.05388193e-02 4.69510224e-02
 3.32080587e-02 3.25203451e-02 4.66293360e-02 3.61019144e-02
 4.53634379e-02 8.50091881e-01 4.56768096e-02 8.77194258e-01
 4.09020477e-02 3.16247736e-02 4.38270669e-02 4.11859296e-02
 2.65454297e-02 4.96014853e-02 4.23404218e-02 4.76007352e-02
 2.84742479e-02 8.70841988e-01 7.54609403e-02 8.15007386e-01
 3.11859799e-02 3.39098058e-02 2.50944406e-02 1.67772514e-02
 2.74934071e-02 3.56032843e-02 4.59922418e-02 4.20489313e-02
 2.96961417e-02 2.58100107e-02 5.92265014e-02 4.47428279e-02
 1.90587694e-02 8.73256255e-01 3.81644526e-02 3.58517647e-02
 5.57114233e-02 4.29292066e-02 8.49170417e-01 2.47439401e-02
 8.41630287e-01 8.26671642e-01 8.58177559e-01 3.73780642e-02
 8.64212002e-01 8.87664202e-01 3.09687983e-02 2.37208308e-02
 4.35258068e-02 3.14046353e-02 3.79005735e-02 3.48677564e-02
 2.49185898e-02 3.22941806e-02 3.01146246e-02 4.50521147e-02
 2.04550299e-02 1.13457194e-02 4.00616000e-02 1.70168720e-02
 2.40571964e-02 2.27390386e-02 2.01679886e-02 2.86744531e-02
 2.52715002e-02 3.03260035e-02 2.14915157e-02 2.94890196e-02
 3.84300954e-02 3.07530812e-02 2.99046737e-02 2.24206800e-02
 3.43855641e-02 2.03110127e-02 8.72455816e-01 2.73012161e-02
 2.19512925e-02 2.71103313e-02 8.71651065e-01 2.54497765e-02
 1.27159239e-02 8.93976075e-01 2.42271194e-02 2.35543731e-02
 1.86584217e-02 2.32248707e-02 1.82663270e-02 2.59919845e-02
 2.92832986e-02 1.39484656e-02 8.44493084e-01 1.75062455e-02
 2.78817406e-02 1.65409482e-02 1.89243929e-02 2.90789697e-02
 1.81374345e-02 2.00259511e-02 4.32265239e-02]

######################

APARTMENTS_AVG   [0.0247 0.0959    nan ... 0.0261 0.0731 0.3466]

######################

BASEMENTAREA_AVG   [0.0369 0.0529    nan ... 0.274  0.2733 0.636 ]

######################

YEARS_BEGINEXPLUATATION_AVG   [0.9722 0.9851    nan 0.9811 0.9806 0.9985 0.9881 0.9781 0.9786 0.9876
 0.9861 0.9732 0.9831 0.9697 0.9901 0.9801 0.9762 0.996  0.998  0.9846
 0.9886 0.9354 0.9841 0.9856 0.9955 0.9677 0.9891 0.9752 0.9826 0.9727
 0.6508 0.9578 0.9742 0.9707 0.9975 0.999  0.9816 0.9866 0.9836 0.994
 0.9757 0.9737 0.9791 0.9821 0.9682 0.995  0.9771 0.9945 0.9747 0.9776
 0.9796 0.9896 0.9692 0.9518 0.9995 0.9414 0.993  0.9702 0.9921 0.9916
 0.9712 0.4933 0.9871 0.9672 0.9911 0.9608 0.9906 0.9503 0.9598 0.997
 0.9583 0.9767 0.929  0.9935 0.9617 0.9563 0.9965 0.9925 0.9508 0.9717
 0.9687 0.9667 0.9359 0.9573 0.9588 0.9513 0.9642 0.9553 0.9603 0.9543
 0.9622 0.9637 0.3224 0.9568 0.6538 0.9652 0.9523 0.4953 0.9473 0.
 0.9071 0.9593 0.9627 0.9613 0.9439 0.9434 0.9488 0.4973 0.9459 0.9334
 0.9657 0.9632 0.9424 0.9548 0.9449 0.4913 0.9647 0.9662 0.9468 0.3284
 0.9001 0.9324 0.9389 1.     0.9493 0.9463 0.9498 0.92   0.4903 0.9121
 0.9444 0.3259 0.9409 0.9384 0.4848 0.9329 0.9429 0.928  0.9483 0.9478
 0.9538 0.9379 0.9404 0.4759 0.8977 0.7442 0.927  0.9528 0.8927 0.9344
 0.3279 0.9275 0.9056 0.9558 0.4983 0.4883 0.9339 0.7432 0.7829 0.6533
 0.9136 0.1987 0.9195 0.9419 0.9319 0.9175 0.5315 0.9309 0.9305 0.9349
 0.6841 0.9399 0.9066 0.926  0.4943 0.9394 0.9245 0.3294 0.9295 0.8674
 0.229  0.8579 0.5852 0.4863 0.9454 0.93   0.9235 0.916  0.9314 0.9369
 0.924  0.6513 0.3304 0.8877 0.8922 0.3289 0.921  0.9106 0.9533 0.3254
 0.4779 0.9151 0.4978 0.4898 0.7914 0.4893 0.0979 0.6344 0.5857 0.9374
 0.9096 0.4938 0.918  0.8967 0.4918 0.4853 0.7437 0.925  0.9225 0.6577
 0.923  0.9215 0.8276 0.6567 0.6547 0.8992 0.2434 0.9364 0.1942 0.4968

In [9]:
col_path = "HomeCredit_columns_description.csv"
df = pd.read_csv(os.path.join(data_dir, col_path))
df.head(20)

,col_id,Table,Row,Description,Special
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN
10,13,application_{train|test}.csv,AMT_GOODS_PRICE,For consumer loans it is the price of the good...,NaN
11,14,application_{train|test}.csv,NAME_TYPE_SUITE,Who was accompanying client when he was applyi...,NaN
12,15,application_{train|test}.csv,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat...",NaN
13,16,application_{train|test}.csv,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN
14,17,application_{train|test}.csv,NAME_FAMILY_STATUS,Family status of the client,NaN
15,18,application_{train|test}.csv,NAME_HOUSING_TYPE,What is the housing situation of the client (r...,NaN
16,19,application_{train|test}.csv,REGION_POPULATION_RELATIVE,Normalized population of region where client l...,normalized
17,20,application_{train|test}.csv,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application
18,21,application_{train|test}.csv,DAYS_EMPLOYED,How many days before the application the perso...,time only relative to the application
19,22,application_{train|test}.csv,DAYS_REGISTRATION,How many days before the application did clien...,time only relative to the application

In [11]:
col_path = "bureau.csv"

df = pd.read_csv(os.path.join(data_dir, col_path))
for col  in df.columns:
    print(col," ",df[col].unique())
    print("\n######################\n")

SK_ID_CURR   [215354 162297 402440 ... 448157 345866 235871]

######################

SK_ID_BUREAU   [5714462 5714463 5714464 ... 5057762 5057770 5057778]

######################

CREDIT_ACTIVE   ['Closed' 'Active' 'Sold' 'Bad debt']

######################

CREDIT_CURRENCY   ['currency 1' 'currency 2' 'currency 4' 'currency 3']

######################

DAYS_CREDIT   [-497 -208 -203 ...    0   -3   -1]

######################

CREDIT_DAY_OVERDUE   [   0 2603    6   30 2156  496  186 2264   41    8   71   13  252 1201
   12   38 1777  150   18   37   64 2050    9    4   29   22   49 1930
   34  951  936  664   45 2625  837   21   15   31 1715   19   67    7
   26   23   48   46   73   90 1127   53   33 1572   39 2582   14   25
   10   50   17  193   40   20   28  123  138  700  122 1504   32  670
   75  140   24  277 2019  161  962  187   58  106  634   83  120   60
   93 1694  227   44  344 2085 1248  124 1651 2541 1541  642  745  163
  234 1472  688 2455  614  319 2187   68  831  139  283  180   47  164
  174 1604 1326 2149   36   62  753  374 1573 1562 2400   35  860   11
  776  520   77 1892 1786   80 2310 2383  136  264  131    5 2571 1579
  198 2534 2292   63   72 2238 1475 2614  107    3 1195  990 1430  242
  249   16  648  659  100 2210 2249   57  672 2765   52 1899  676   43
   27  288   69 1222 2246  108  149 1087  212  256  192  211 2476  144
  141  650  110  372  948  651 1674 2188   76 2620   82  117 1428 2481
  104  216   91  618  635 2133 1409  226 1903 2592  338  155 2041   42
   54  143 1632  625  132  225  890  165  241 1747   78  719 1760  152
 1714  363 1406 1032 1307   66  477 1058   88  621 2463   81 1501  669
 1727  102   84  103  418  586 2364 2693 1272 2524 2030 1729 2069  171
 1417 2527  668 2129    2 2537  175  199  356   56 1761 1704  433   61
  209  652 1769 1455  893  183 1142 1172 1695  126 1319  817 1077 1862
 1601 1482 1018 2349 2312 1100   99 1620   98   55   59 2442  646 2499
  865 2234   51 2331 1150 1179   79 1072  819  480 2384   85  895 1062
  245 1554  127 1796 1506    1  114 2141   86 2195  237  592  388 2640
 2610 2282 1982  397 1118  458 1097  159 2544  952 1973   97 1591 1650
  653 1678  172 1529 2586  612  879  101 1240 1038 1587  157 1381 1088
  691 2602  345  748 1881 1474  986  208 1000  639 1403  640  328 2270
   65  128  276 2078  846  907  632 1452 2638  686 1036   74 1244  552
 1774 1763 2700  870  204 2456  177 2580  610  638   87  210  943 1927
 2184 2165  671 1733 2685 2243 2585 2466 2254 1590  195 2397 2595   94
  677  666  105  235  366  273  142 2770 2679 2379  445  724 2121 1921
 1814  221  403  243 2137  296 1011 1637  991 1829 1162 1684 1857  364
 2317  334  285  588  649  224 1499 1680  689 1512 2644  981 1997  213
 1826 2542 1570  219  244  611 1445  188  278  707 2193  179 2299 1919
 2092 1770 2599 2340  166 1275 1540 1469 2354 1671  169 2348 1233  752
  160  493 1047 1845 1206  738 1943 2347 2473  718 2629 2134  872 2168
 2080  268 2781   95  547 1835  115   70 2598  730 1681 2703 2324 2289
  190 2028 1618   89 2581  153 1764 2609 2395 2529 2652  135  414  206
  953  605 2108 1719 2565 2623  147  932 2754 1232 1178 2138 1199 2574
   92  238 1001  312  214 1468  934 2657  337 2279 1074  519 1075  641
  473  341  321 1051 2286 1226 1338 2275  960 1061  158  373  673 2391
 2221  429 2018  130 1993 2034 2358  112  326 2484 2616 1947 1742 1631
 1629  544 1463 1073 2048 1049  220  643  615  154  423 2217 1682 1131
 1086 2553  606 2071 2684  761 1009  358 2440  476 2513  232  630 1055
  133 1667  113 1875  441  768  181 1397 2332 1737 1290  148 1635  680
  714 1325 1521 1522 2059 1724 1313 1740 2277 1352  994 1104 2776 2211
 1042 2325 2600  426 2552  877 1670 1711  733  119 2656 2360 1235 1093
 1031 1197 2290  920 1887 1530 2117 2591  927  265  737 2464 1644  685
  723 2677 2588  647  631 1350  325  550 2212  756 1939 1167  362  251
 2058  891  781 1502 1205  931  944  121  525 1116 1068  747  472 1285
  452  619 2164  368 1524 2214 1907 1759  280 1274  969 1363 2335  303
 1936 1247 1552 1177  938  261  910  170  996 1252  827 1736  679  982
  731  720  674  919 1388  717 2029 2631 2502 2298  830 1638  146 2649
  915  247  806 1634 2252 1200 1218 1408  413 2295 2667  537  616 1364
  422 2353 2066  599  656 2474 2637  437 2643 2201 2175  289 1189 2661
  109 2338 1776  348 2102 2053  314  974  985  292 2099  810 1813 1334
 1095  137 1489  125 1253 1548  502  848 2258 1720 1804 1299  455 1194
  189  929 1706  584  942 1420 1213  134  290  269 2272  657 1766  217
 2128  408 1822 2627  593  129  231  178 1020  191 2577  485 1961  406
 1503 1703 2057 2641  795 1901 2093 1752  320  317 1255 1523 2228  933
 2766 1612  995  162 1843  694 2176  168 1648 2606 1209 1505  514 1797
  116 2546 2146  504 1755 1692 1722  200   96 2157  531 1962 1480  743
 2688 1588 1402  284  440  678 2280 1171  629  467 1135  786  976 1393
 2545 1161 2394 1404  176 2220 1183 2497 1972  873  299  787 1156  118
 1739 1060 2426 2604 2792  883 2355 2061 1584  465 1556 2301  275 1859
  184 1546  687  439 2634 2540  291 1496 1514 1193 2639 2608 2651 1754
 1918 1858 1298  554  876  323 2528 2681 2496 2109  324  765 2256 1278
 2284 2536 1693 1398 1912  826 2107  167  515  407 1863  460 1158  727
 1610 2204 2654 1931]

######################

DAYS_CREDIT_ENDDATE   [-153. 1075.  528. ... 5922. 3835. 5650.]

######################

DAYS_ENDDATE_FACT   [ -153.    nan -1710. ... -2919. -3042. -2891.]

######################

AMT_CREDIT_MAX_OVERDUE   [      nan 77674.5       0.    ...   173.07  11317.59   5693.625]

######################

CNT_CREDIT_PROLONG   [0 2 1 4 3 5 9 8 6 7]

######################

AMT_CREDIT_SUM   [ 91323.   225000.   464323.5  ...  77861.43 112204.35 108765.72]

######################

AMT_CREDIT_SUM_DEBT   [      0.     171342.            nan ...  830860.875  146502.
 1092226.5  ]

######################

AMT_CREDIT_SUM_LIMIT   [       nan 108982.62       0.    ...  10398.15   10617.75  135035.865]

######################

AMT_CREDIT_SUM_OVERDUE   [    0.      231.525   288.    ...   804.735 22581.      352.62 ]

######################

CREDIT_TYPE   ['Consumer credit' 'Credit card' 'Mortgage' 'Car loan' 'Microloan'
 'Loan for working capital replenishment' 'Loan for business development'
 'Real estate loan' 'Unknown type of loan' 'Another type of loan'
 'Cash loan (non-earmarked)' 'Loan for the purchase of equipment'
 'Mobile operator loan' 'Interbank credit'
 'Loan for purchase of shares (margin lending)']

######################

DAYS_CREDIT_UPDATE   [  -131    -20    -16 ...  -2901 -41918  -2844]

######################

AMT_ANNUITY   [      nan     0.     2691.    ...  7681.95   4482.585 24351.435]

######################

In [12]:
col_path = "bureau_balance.csv"


df = pd.read_csv(os.path.join(data_dir, col_path))
for col  in df.columns:
    print(col," ",df[col].unique())
    print("\n######################\n")

SK_ID_BUREAU   [5715448 5715449 5715451 ... 5041172 5041332 5041336]

######################

MONTHS_BALANCE   [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20 -21 -22 -23 -24 -25 -26 -27 -28 -29 -30 -31 -32 -33 -34 -35
 -36 -37 -38 -39 -40 -41 -42 -43 -44 -45 -46 -47 -48 -49 -50 -51 -52 -53
 -54 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64 -65 -66 -67 -68 -69 -70 -71
 -72 -73 -74 -75 -76 -77 -78 -79 -80 -81 -82 -83 -84 -85 -86 -87 -88 -89
 -90 -91 -92 -93 -94 -95 -96]

######################

STATUS   ['C' '0' 'X' '1' '2' '3' '5' '4']

######################

In [16]:
col_path = "installments_payments.csv"

df = pd.read_csv(os.path.join(data_dir, col_path))
for col  in df.columns:
    print(col," ",df[col].unique())
    print("\n######################\n")

SK_ID_PREV   [1054186 1330831 2085231 ... 1984920 1946334 1276288]

######################

SK_ID_CURR   [161674 151639 193053 ... 413433 434445 405063]

######################

NUM_INSTALMENT_VERSION   [  1.   0.   2.   4.   3.   5.   7.   8.   6.  13.   9.  21.  22.  12.
  17.  18.  11.  14.  34.  33.  19.  16.  15.  10.  26.  27.  20.  25.
  23.  24.  31.  32.  28.  35.  29.  30.  43.  39.  40.  36.  41.  42.
  37.  38.  68.  44.  45.  46. 178.  52.  51.  53.  54.  49.  50.  58.
  57.  55.  56.  48.  47.  72.  59.  73.  61.]

######################

NUM_INSTALMENT_NUMBER   [  6  34   1   3   2  12  11   4  14   8  20  56   7  23  38 116   5  46
 106   9 105  88  30  16  65  19  15  57  10  41  84  49  59 107  17  94
  64  28  24 140  43  99  69  13  22  85  29  83  73 139  39  18  26  25
  21  44  27  31  37  63  45  78  53  92 112  36  93 114  58  32  67  47
  68  40  81  61 117  60  75 149  35  48  82  79  71  51  72  80 156  42
  50 148  33  55 103  54 180  86 113  87  62 102 115 142 164 162 101  91
  96 100 104 121  66 123  52  89  70 124  76  97 134 165 135  77 128 125
 118 122 153  95 109 158 132 120 111 151 133 119 129  98 173 127  90 168
 138  74 150 108 145 147 152 130 146 154 196 210 110 144 136 170 190 126
 191 171 131 178 155 157 181 183 169 137 207 143 163 159 195 200 177 176
 187 184 198 167 141 175 160 161 188 185 186 182 174 194 179 197 216 172
 189 208 237 166 203 217 205 202 199 204 231 192 220 201 211 193 209 227
 206 221 213 219 244 214 229 233 224 218 226 222 230 215 212 228 223 225
 240 235 234 239 232 236 238 242 241 252 273 271 275 254 269 256 251 247
 248 266 262 263 265 253 245 250 268 260 243 264 261 255 246 267 249 259
 257 272 258 270 277 274 276]

######################

DAYS_INSTALMENT   [-1.180e+03 -2.156e+03 -6.300e+01 ... -2.921e+03 -2.551e+03 -1.000e+00]

######################

DAYS_ENTRY_PAYMENT   [-1187. -2156.   -63. ... -3023. -3061. -3096.]

######################

AMT_INSTALMENT   [  6948.36    1716.525  25425.    ...  22427.46  344249.955  43737.435]

######################

AMT_PAYMENT   [  6948.36    1716.525  25425.    ... 144843.48   53710.02   46517.49 ]

######################